package main

import (
	"bytes"
	"encoding/csv"
	"flag"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

type permission struct {
	Code string
	Name string
}

func main() {
	input := flag.String("input", "permissions", "directory containing permission CSV files")
	output := flag.String("output", "security/permissions/permissions.go", "generated Go file path")
	tsOutput := flag.String("ts-output", "", "generated TypeScript file path")
	pkg := flag.String("package", "permissions", "generated Go package name")
	flag.Parse()

	permissions, err := readPermissions(*input)
	if err != nil {
		fatal(err)
	}

	content, err := generate(*pkg, permissions)
	if err != nil {
		fatal(err)
	}

	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		fatal(err)
	}

	if err := os.WriteFile(*output, content, 0o644); err != nil {
		fatal(err)
	}

	if strings.TrimSpace(*tsOutput) != "" {
		tsContent, err := generateTypeScript(permissions)
		if err != nil {
			fatal(err)
		}

		if err := os.MkdirAll(filepath.Dir(*tsOutput), 0o755); err != nil {
			fatal(err)
		}

		if err := os.WriteFile(*tsOutput, tsContent, 0o644); err != nil {
			fatal(err)
		}
	}
}

func readPermissions(root string) ([]permission, error) {
	byCode := map[string]string{}

	err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || filepath.Ext(filePath) != ".csv" {
			return nil
		}

		file, err := os.Open(filePath)
		if err != nil {
			return err
		}
		defer file.Close()

		reader := csv.NewReader(file)
		reader.TrimLeadingSpace = true
		rows, err := reader.ReadAll()
		if err != nil {
			return fmt.Errorf("read %s: %w", filePath, err)
		}

		for i, row := range rows {
			rowNumber := i + 1
			if len(row) != 2 {
				return fmt.Errorf("%s:%d: expected 2 columns", filePath, rowNumber)
			}

			code := strings.TrimSpace(row[0])
			if code == "" {
				return fmt.Errorf("%s:%d: empty permission code", filePath, rowNumber)
			}

			name := constName(code)
			if existing, ok := byCode[code]; ok {
				return fmt.Errorf("duplicate permission %q: %s and %s", code, existing, name)
			}

			byCode[code] = name
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	out := make([]permission, 0, len(byCode))
	usedNames := map[string]string{}
	for code, name := range byCode {
		if existing, ok := usedNames[name]; ok {
			return nil, fmt.Errorf("permissions %q and %q generate the same constant %q", existing, code, name)
		}

		usedNames[name] = code
		out = append(out, permission{Code: code, Name: name})
	}

	sort.Slice(out, func(i, j int) bool {
		return out[i].Code < out[j].Code
	})

	return out, nil
}

func generate(pkg string, permissions []permission) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by scripts/generate-permissions.sh; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	fmt.Fprintf(&buf, "const (\n")
	for _, permission := range permissions {
		fmt.Fprintf(&buf, "\t%s = %q\n", permission.Name, permission.Code)
	}
	fmt.Fprintf(&buf, ")\n")

	return format.Source(buf.Bytes())
}

func generateTypeScript(permissions []permission) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by scripts/generate-permissions.sh; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "export const permissionCodes = [\n")
	for _, permission := range permissions {
		fmt.Fprintf(&buf, "  %q,\n", permission.Code)
	}
	fmt.Fprintf(&buf, "] as const;\n\n")
	fmt.Fprintf(&buf, "export type PermissionCode = (typeof permissionCodes)[number];\n\n")
	fmt.Fprintf(&buf, "export const Permissions = {\n")
	for _, permission := range permissions {
		fmt.Fprintf(&buf, "  %s: %q,\n", lowerCamel(permission.Name), permission.Code)
	}
	fmt.Fprintf(&buf, "} as const;\n")

	return buf.Bytes(), nil
}

func constName(code string) string {
	var out strings.Builder
	capitalizeNext := true

	for _, r := range code {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			if capitalizeNext {
				out.WriteRune(unicode.ToUpper(r))
			} else {
				out.WriteRune(r)
			}
			capitalizeNext = false
			continue
		}

		capitalizeNext = true
	}

	name := out.String()
	if name == "" {
		return "Permission"
	}

	return name
}

func lowerCamel(value string) string {
	if value == "" {
		return value
	}

	runes := []rune(value)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
